config/routes.rb
Rails.application.routes.draw do

  # show all
  get "/tasks", to: "tasks#index", as: :tasks

  # create a task
  get "/tasks/new", to: "tasks#new", as: :new_task
  post "/tasks", to: "tasks#create"

  # show one task
  get "tasks/:id", to: "tasks#show", as: :task

  # edit task
  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to: "tasks#update"

  # destroy
  delete '/tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render "new", status: unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy()
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.label :details %>
  <%= f.text_field :details, class: "form-control" %>
  <%= f.submit 'Add Task', class: 'btn btn-success mt-3' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.label :details %>
  <%= f.text_field :details, class: "form-control" %>
  <%= f.check_box :completed %>
  <%= f.label :completed, "Mark Complete" %>
  <br>
  <%= f.submit 'Edit Task', class: 'btn btn-success mt-3' %>
<% end %>
<%= link_to "Back to List", tasks_path %>

app/views/tasks/index.html.erb
<h1>All Your Tasks</h1>
<ul class="tasks" style="list-style-type: none">
  <% @tasks.each do |task| %>
    <li>
    <input type="checkbox">
    <%= link_to task.title, task_path(task) %>
    <%# <a href="" data-turbo-method='delete'></a> %>
    <%= link_to task_path(task), data: { turbo_method: :delete, turbo_confirm: "Delete #{task.title}?" } do %>
    <i class="fa-solid fa-trash"></i>
    <% end %>
  <% end %>
    </li>
</ul>
<br>
<%= link_to "Add a new Task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Add a new Task</h1>
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
  <%= f.label :details %>
  <%= f.text_field :details, class: "form-control" %>
  <%= f.submit 'Add Task', class: 'btn btn-success mt-3' %>
<% end %>
<%= link_to "Back to List", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= link_to "Edit This Task", task_edit_path(@task) %>
<p class="text-gray"><%= @task.details %></p>
<p class="text-gray">
  <% if @task.completed %>
  <%= "Task is completed" %>
  <% else %>
  <%= "Task is not completed" %>
  <% end %>
</p>